[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "*"
[[redirects]]
  from = "/"
  to = "https://www.mihoyo.com"
  status = 301
  force = true
[[redirects]]
  from = "/v1beta/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true
